apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: myclaim
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: microk8s-hostpath
