apiVersion: v1
kind: Service
metadata:
  name: jupyter2
  labels:
    app: jupyter2
spec:
  type: NodePort
  selector:
    app: jupyter2
  ports:
  - port: 80
    name: http
    targetPort: 8888
    nodePort: 32583
---
apiVersion: v1
kind: Pod
metadata:
  name: jupyter2
  labels:
    app: jupyter2
spec:
  containers:
    - name: jupyter2
      image: jupyter/minimal-notebook
      ports:
      - containerPort: 8888
        protocol: TCP
        name: http
      volumeMounts:
      - mountPath: /jupyter
        name: jupyter2

  volumes:
  - name: jupyter2
    persistentVolumeClaim:
      claimName: myclaim
