apiVersion: v1
kind: Service
metadata:
  labels:
    run: port-test-webapp
  name: port-test-webapp
  namespace: default
spec:
  ports:
  - nodePort: 30665
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: port-test-webapp
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
