apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-frontend
  name: simple-frontend-service
  namespace: default
spec:
  ports:
  - nodePort: 32309
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: simple-frontend
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
