apiVersion: v1
kind: Service
metadata:
  name: sample-nginx
  labels:
    app: sample-nginx
spec:
  type: NodePort
  selector:
    app: sample-nginx
  ports:
  - port: 80
    name: http
    targetPort: 80
    nodePort: 30630
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sample-nginx
  name: sample-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sample-nginx
    spec:
      containers:
      - image: nginx:1.16
        name: nginx
        resources: {}
status: {}
